apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: app1-dev.localhost
    http:
      paths:
      - backend:
          service:
            name: service
            port:
              number: 4000
        path: /
        pathType: ImplementationSpecific