apiVersion: kubernetes.example.com/v1alpha1
kind: WebApp
metadata:
  name: app1-dev
  namespace: default
spec:
  applicationName: app1
  environment: dev
  image: "ghcr.io/nkzk/example-go-image:release"
  host: app1-dev.localhost
