apiVersion: kubernetes.example.com/v1alpha1
kind: WebApp
metadata:
  name: app1-prod
  namespace: default
spec:
  applicationName: app1
  environment: prod
  image: "quay.io/avulaj/web-service-gin:latest"
  hostName: app1-prod.localhost
