apiVersion: kubernetes.example.com/v1alpha1
kind: WebApp
metadata:
  name: app1-prod
  namespace: default
spec:
  applicationName: app1
  environment: prod
  image: "ghcr.io/nkzk/example-go-image:release"
  host: app1-prod.localhost
