resources:
  - ../../iac/kubernetes/base
  - gitops/ingress.yaml

namespace: example
namePrefix: app1-

images:
- name: registry.example.io
  newName: ghcr.io/nkzk/example-go-image
  newTag: release

labels:
- pairs:
    app: app1
  includeSelectors: true

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: deployment
    spec:
      template:
        spec:
          containers:
          - name: app
            env:
            - name: ENVIRONMENT
              value: production
            ports:
            - containerPort: 4000
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: service
    spec:
      ports:
      - port: 4000
        targetPort: 4000
