resources:
  - ../../iac/kubernetes/base

namespace: default
namePrefix: app2-

images:
- name: registry.example.io
  newName: ghcr.io/nkzk/example-go-image
  newTag: release

labels:
- pairs:
    app: app2
  includeSelectors: true

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: deployment
    spec:
      template:
        spec:
          containers:
          - name: app
            resources:
              limits:
                memory: "2Gi"
                cpu: "50m"