apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: application
  template:
    spec:
      containers:
      - name: app
        image: registry.example.io
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
