# alt under src/<appname>
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Intility/gitops-monorepo-crossplane.git
      revision: HEAD
      directories:
      - path: src/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: example # '{{path.basename}}'
    spec:
      project: "default"
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/Intility/gitops-monorepo-crossplane.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
